rest:
  api:
   base.path: api
---
spring:
  profiles: local,default
  application:
    name: elearning
  data:
    mongodb:
     uri: mongodb://simulator:simulator@ds119395.mlab.com:19395/simulator
  security:
    basic:
      enabled:false
  messages:
    basename: messages
    encoding: UTF-8
  
---
mongo:
  min-connections: 2
  max-connections: 5
  connect-timeout-ms: 5000
  socket-timeout-ms: 5000
  
spring:
  profiles: prod
  application:
    name: elearning
  mongodb:
     uri: mongodb://simulator:simulator@ds119395.mlab.com:19395/simulator
  messages:
    basename: messages
    encoding: UTF-8